version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - whatsapp-net

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword       # root user password
      MYSQL_DATABASE: whatsapp_db             # auto-created DB
      MYSQL_USER: appuser                     # non-root user
      MYSQL_PASSWORD: appuserpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - whatsapp-net

volumes:
  mysql_data:

networks:
  whatsapp-net:
    driver: bridge
