CREATE TABLE IF NOT EXISTS Users (
  user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100),
  mobile VARCHAR(15) UNIQUE,
  email VARCHAR(50) UNIQUE,
  password_hash VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);